name: Build documentation

on:
  pull_request:
    paths:
      - python/**
      - docs/**
      - mkdocs.yml
      - .github/workflows/docs.yml
  repository_dispatch:
    types:
      - python-release
  # Allow manual trigger for now
  workflow_dispatch:

env:    
  IS_RELEASE: ${{ github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch' }}
  BUILD_ARGS: ${{ (github.event_name == 'repository_dispatch' || github.event_name == 'workflow_dispatch') && 'install MATURIN_EXTRA_ARGS="--manylinux off"' || 'develop' }}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: docs/mlc-config.json
        folder-path: docs

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: docs/src/python

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Build and install deltalake
        run: |
          cd python
          make ${{ env.BUILD_ARGS }}

      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt

      - name: Build
        run: |
          mkdocs build

      - name: Deploy
        if: ${{ env.IS_RELEASE == 'true' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          clean-exclude: |
            python/
            .nojekyll
          single-commit: false
          tag: "doc update for tag ${{ github.ref_name }}"


